# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        image_Products:
            quality: 75
            filters:
                thumbnail: { size: [281, 400], mode: outbound }

        image_medaille:
            quality: 75
            filters:
                thumbnail: { size: [200, 400], mode: outbound }
        
        logo_grey:
            quality: 75
            filters:
                thumbnail: { size: [118.05, 166.97], mode: outbound }
        
        image_section_3:
            quality: 75
            filters:
                thumbnail: { size: [463.75, 655.94], mode: outbound }

        logo_delaye:
            quality: 75
            filters:
                thumbnail: { size: [200, 171.47], mode: outbound }
